---
  - name: fwknopd | Install | Check if 'fwknopd' is installed
    command: test -x /usr/sbin/fwknopd
    register: fwknopd_present
    ignore_errors: yes
    tags:
      - fwknopd

  - name: fwknopd | Install | Install 'fwknopd' package
    apt: pkg=fwknop-server state=present
    when: fwknopd_present | failed
    become: yes
    tags:
      - fwknopd

  - name: fknopd | Setup | Define users
    set_fact:
      users: "{{ users | default({}) }}"

  - name: fwknopd | Setup | Create access conf file
    template: src=access.conf.j2 dest=/etc/fwknop/access.conf owner=root group=root mode=0600
    when: users | length > 0
    become: yes
    notify: fwknopd restart
    tags:
      - fwknopd

  - name: fwknopd | Install | Check if 'iptables-persistent' is installed
    command: test -x /etc/init.d/iptables-persistent
    register: iptablespersistent_present
    ignore_errors: yes
    tags:
      - fwknopd
      - iptables-persistent

  - block:
    - name: fwknopd | Install | iptables-persistent | Answer install dialog questions
      debconf: name=iptables-persistent question={{item}} vtype=boolean value=true
      with_items:
        - iptables-persistent/autosave_v4
        - iptables-persistent/autosave_v6

    - name: fwknopd | Install | iptables-persistent | Install package
      apt: name=iptables-persistent state=present

    when: iptablespersistent_present | failed
    become: yes
    tags:
      - fwknopd
      - iptables-persistent
